/**
 * The ADAPTER — a KnowledgeGraph over a JSON file the Python side wrote.
 *
 * `data/graph-export.json` stands in for dev_graph's `graph.json`: an
 * offline projection of the markdown graph, regenerated by a script and
 * never hand-edited. The real exporter is Python and stays Python (MISSION:
 * Python's territory). Hermes only ever sees its output, as bytes.
 *
 * Bytes another program wrote are untrusted (lesson 0005), so the file is
 * parsed against `ExportSchema` before anything else happens. That schema
 * is written in dev_graph's vocabulary on purpose: snake_case, canonical
 * ids, its own closed lists. The translation into Hermes's words happens
 * once, in `toItem`, and nowhere else. Three translations, as in lesson
 * 0006's adapter:
 *
 *   1. a row's `source_paths` + `related_decisions` → `sources` (attribution)
 *   2. the file's `exported_at`                    → `generatedBy` (generation)
 *   3. the snapshot name + `canonical_id`          → `derivedFrom` (derivation)
 *
 * `confidence` crosses untranslated. The five labels are dev_graph's, and
 * Hermes adopts them rather than inventing a second scale.
 */
import { readFileSync } from "node:fs";
import { z } from "zod";
import {
  ConfidenceSchema,
  EvidenceItemSchema,
  type EvidenceBundle,
  type EvidenceItem,
  type Source,
} from "./evidence.js";
import type { KnowledgeGraph } from "./graph-port.js";

// ── The boundary: dev_graph's shape, not Hermes's ───────────────────────

const ExportRowSchema = z.object({
  canonical_id: z.string().min(1),
  slug: z.string().min(1),
  title: z.string().min(1),
  type: z.enum(["module", "contract"]),
  status: z.enum(["implemented", "prepared", "planned"]),
  confidence: ConfidenceSchema,
  source_paths: z.array(z.string().min(1)),
  related_decisions: z.array(z.string().min(1)),
  updated: z.iso.date(),
  depends_on: z.array(z.string().min(1)),
});

export const ExportSchema = z.object({
  exported_by: z.string().min(1),
  exported_at: z.iso.datetime(),
  snapshot: z.string().min(1),
  nodes: z.array(ExportRowSchema),
});

export type GraphExport = z.infer<typeof ExportSchema>;
type ExportRow = z.infer<typeof ExportRowSchema>;

export type ParseOutcome<T> = { ok: true; value: T } | { ok: false; issues: string };

/** The parse. Untyped JSON in, a typed export or a readable issue list out. */
export function parseExport(raw: unknown): ParseOutcome<GraphExport> {
  const result = ExportSchema.safeParse(raw);
  return result.success
    ? { ok: true, value: result.data }
    : { ok: false, issues: z.prettifyError(result.error) };
}

/** Read and parse a file. Throws, because a bad export is a wiring fault. */
export function loadExport(path: URL | string): GraphExport {
  const raw: unknown = JSON.parse(readFileSync(path, "utf8"));
  const parsed = parseExport(raw);
  if (!parsed.ok) throw new Error(`graph export rejected:\n${parsed.issues}`);
  return parsed.value;
}

// ── The adapter ─────────────────────────────────────────────────────────

/** ISO timestamp supplier. Injected so a test can pin `assembledAt`. */
export type Clock = () => string;

/** A row and the item translated from it, kept side by side: search matches
 * on the row's slug and title, and answers with the item. */
interface Entry {
  row: ExportRow;
  item: EvidenceItem;
}

export class JsonExportAdapter implements KnowledgeGraph {
  static readonly NAME = "JsonExportAdapter";
  private readonly entries: Entry[];
  private readonly snapshot: string;

  constructor(graph: GraphExport, private readonly clock: Clock = () => new Date().toISOString()) {
    this.snapshot = graph.snapshot;
    // Translate once, at construction, and parse every item against the
    // evidence schema on the way. A row that breaks a cross-field rule
    // (confirmed on one source) is refused here, before any query can
    // return it.
    this.entries = graph.nodes.map((row) => {
      const parsed = EvidenceItemSchema.safeParse(toItem(row, graph.snapshot, graph.exported_at));
      if (!parsed.success) {
        throw new Error(`row ${row.canonical_id} rejected:\n${z.prettifyError(parsed.error)}`);
      }
      return { row, item: parsed.data };
    });
  }

  async search(query: string, limit: number): Promise<EvidenceBundle> {
    const needle = query.toLowerCase();
    const items = this.entries
      .filter(
        ({ row }) =>
          row.canonical_id.toLowerCase().includes(needle) ||
          row.slug.toLowerCase().includes(needle) ||
          row.title.toLowerCase().includes(needle),
      )
      .slice(0, limit)
      .map(({ item }) => item);
    return {
      query,
      assembledAt: this.clock(),
      assembledBy: { adapter: JsonExportAdapter.NAME, snapshot: this.snapshot },
      items,
    };
  }

  async node(id: string): Promise<EvidenceItem | undefined> {
    return this.entries.find(({ item }) => item.id === id)?.item;
  }

  async all(): Promise<EvidenceItem[]> {
    return this.entries.map(({ item }) => item);
  }
}

// ── The translation ─────────────────────────────────────────────────────

/** One row in dev_graph's words becomes one item in Hermes's. */
function toItem(row: ExportRow, snapshot: string, exportedAt: string): unknown {
  const sources: Source[] = [
    ...row.source_paths.map((ref) => ({ kind: "code" as const, ref })),
    ...row.related_decisions.map((ref) => ({ kind: "adr" as const, ref })),
  ];
  return {
    id: row.canonical_id,
    // Templated, so two exports of the same row give the same sentence.
    claim: `${row.title} is ${row.status} (${row.type}).`,
    provenance: {
      sources,
      generatedBy: { activity: "graph-export", at: exportedAt },
      derivedFrom: [`${snapshot}#${row.canonical_id}`],
      confidence: row.confidence,
    },
  };
}
